version: '3.7'

services:
  front:
    image: $IMAGE_NAME:$IMAGE_TAG
    container_name: [[__PROJECT_NAME__]]-front
    restart: always
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - $PWD/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - $PWD/config/privkey.pem:/etc/nginx/ssl/privkey.pem
      - $PWD/config/cert.pem:/etc/nginx/ssl/cert.pem
    networks:
      [[__PROJECT_NAME__]]-front-network:

networks:
  [[__PROJECT_NAME__]]-front-network: